export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
// export const PAGINATE = "PAGINATE";
export const ORDER = "ORDER";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
